import type { Metadata } from 'next'
// eslint-disable-next-line camelcase
import { Public_Sans, Source_Sans_3 } from 'next/font/google'
import './globals.scss'

const publicSans = Public_Sans({
  subsets: ['latin'],
  variable: '--font-public-sans',
})
const sourceSans3 = Source_Sans_3({
  subsets: ['latin'],
  variable: '--font-source-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${publicSans.variable} ${sourceSans3.variable}`}>
        {children}
      </body>
    </html>
  )
}
